<<<<<<< HEAD
markdown: redcarpet
highlighter: rouge
exclude: ['README.md', 'prepros-6.config']
=======
# Build settings
markdown: rouge
highlighter: rouge
>>>>>>> c51e71ed415c9541fc4e11c95d5d7875310ec550
